export const sharedConfig = {
  profileDirectory: 'public/upload/profile/',
  advertisementDirectory: 'public/upload/advertisement/',
  contactDirectory: 'public/upload/contact/',
  viewDirectory: 'public/upload/view/',
  newsDirectory: 'public/upload/news/',
  chatPrivateDirectory: 'public/upload/chat_private/',
  chatRoomDirectory: 'public/upload/chat_room/',
  appRoot: './',
  uploadRoot: './public/upload/',
  publicRoot: './public/',
  sms: {
    cellPhoneNumber: 5000299556794,
    blackSharePhoneNumber: 50002910001080,
    sharePhoneNumber: 5000248725,
    userName: 'paliz3d',
    password: 'yasinwxyz1234',
    smsClass: 1,
  },
  pusher: {
    authKey: '3bf76050d243c21ee0ce',
    secret: '1c4700de2627dfbd5b7d',
    appId: 1163012,
    cluster: 'ap2',
    useTLS: true,
  },
};
